### ISSUE TITLE
Error when parsing "context_articles.json"

### ISSUE THREAD

**Issue by ChewKokWah** [jferguson144/IIRC-baseline#1]
I tried to open the file "context_articles.json" you shared on AllenNLP homepage by first download it to local and use codes below to open:

with open("context_articles.json", encoding="utf-8") as f:
  for count, line in enumerate(f,start=1):
    article = json.loads(line.strip())

It end up giving error below:
JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by jferguson144** [comment]
Your code is trying to read each line in the file as a json object, but the entire file is the object. You can just use:

```
with open("context_articles.json", encoding="utf-8) as f:
  data = json.load(f)
```

**Comment by ChewKokWah** [comment]
Thanks for your help.
